---
dist: bionic
sudo: required
language: python
python:
  - "3.7"
services:
  - docker

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS: 1
  matrix:
    - MOLECULE_DISTRO: ubuntu1604
    - MOLECULE_DISTRO: ubuntu1804

before_install:
  - sudo apt-get -qq update
  - pip install --upgrade pipenv

install:
  - yes | pipenv install --dev --deploy

script:
  - pipenv run molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
